# Generated by Django 4.2.1 on 2023-12-24 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('file_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadfile',
            name='title',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
